### ISSUE TITLE
about multi gpus

### ISSUE THREAD

**Issue by chicleee** [xuannianz/SAPD#1]
hi dear @xuannianz ,thanks for sharing your code and  nice work. When i run this code on my 4gpus, with `--gpu 0,1,2,3 ` , ann i add `model = keras.utils.multi_gpu_model(model, gpus=4)` in train.py
error:
`Traceback (most recent call last):
  File "train.py", line 372, in <module>
    main()
  File "train.py", line 330, in main
    model = keras.utils.multi_gpu_model(model, gpus=list(map(int, args.gpu.split(','))))
  File "/home/kp/.conda/envs/keras/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/multi_gpu_utils.py", line 264, in multi_gpu_model
    merged.append(concatenate(outputs, axis=0, name=name))
  File "/home/kp/.conda/envs/keras/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/merge.py", line 705, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/home/kp/.conda/envs/keras/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 824, in __call__
    self._maybe_build(inputs)
  File "/home/kp/.conda/envs/keras/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "/home/kp/.conda/envs/keras/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 306, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/kp/.conda/envs/keras/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/merge.py", line 385, in build
    del reduced_inputs_shapes[i][self.axis]
IndexError: list assignment index out of range
`
I can't fix this problem, can you help me? thanks!

**Comment by xuannianz** [comment]
Hi @chicleee , it does not support multi-gpu training currently.

**Comment by AutumnZ-94** [comment]
@chicleee same error, I tried that either.

I set a break point in python3.7/site-packages/tensorflow_core/python/keras/utils/multi_gpu_utils.py, line 264

the outputs are `['cls_loss', 'regr_loss', 'meta_select_loss', 'classification', 'regression', 'sapd_target', 'sapd_target_1']`

when the `cls_loss `and `regr_loss` run concatenate([layer1, layer2], axis=0) and raise the IndexError, maybe give a init value of `cls_loss `and `regr_loss` ,or limits the dim works

`cls_loss (Lambda)               ()                   0                   `
`__________________________________________________________________________________________________`
`regr_loss (Lambda)              ()                   0           sapd_target[0][1]                `
`__________________________________________________________________________________________________`
`meta_select_loss (Lambda)       (None,)              0           meta_select_target[0][0]   `
